# Generated by Django 5.1.5 on 2025-01-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, unique=True)),
                ('scp_number', models.IntegerField(unique=True)),
                ('channel_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'HID_controller',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(db_index=True)),
                ('facility_code', models.IntegerField(db_index=True)),
                ('issue_code', models.IntegerField(db_index=True)),
                ('card_holder_name', models.CharField(db_index=True, max_length=255)),
                ('card_holder_phone_no', models.CharField(db_index=True, max_length=255, unique=True)),
                ('alvl', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'card',
                'unique_together': {('card_number', 'facility_code')},
            },
        ),
    ]
