# Generated by Django 5.1.5 on 2025-01-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='HID_Card',
        ),
    ]
