# Generated by Django 5.1.5 on 2025-01-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_alter_card_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIDReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acr_number', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'HID_Reader',
            },
        ),
    ]
