# Generated by Django 5.1.5 on 2025-01-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_hidreader'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='unique_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
