# Generated by Django 5.1.5 on 2025-01-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_card_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='csn_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
