# Generated by Django 5.1.5 on 2025-01-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_card_csn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='allot_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
