# Generated by Django 5.1.5 on 2025-01-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_alter_card_facility_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='issue_code',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
