# Generated by Django 5.1.5 on 2025-01-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_alter_card_issue_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='alvl',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_holder_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_holder_phone_no',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
