# Generated by Django 5.1.5 on 2025-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_alter_card_alvl_alter_card_card_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidreader',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
