# Generated by Django 5.1.5 on 2025-01-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_alter_card_alvl_alter_card_card_holder_name_and_more'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_no', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('marks', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_landline', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_dept', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_card', to='controller.card')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_department', to='employee.department')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
