# Generated by Django 5.1.5 on 2025-01-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cpf_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
