# Generated by Django 5.1.5 on 2025-01-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelog',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
