# Generated by Django 5.1.5 on 2025-01-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employeelog_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
