# Generated by Django 5.1.5 on 2025-01-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employeelog_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelog',
            name='active',
        ),
    ]
