# Generated by Django 5.1.5 on 2025-02-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employeelog_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelog',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
