# Generated by Django 5.1.5 on 2025-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employeelog_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
